apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: request.headers["x-forwarded-for"] | "unknown"
    destination: destination.labels["app"] | destination.workload.name | "unknown"
    destinationVersion: destination.labels["version"] | "unknown"
---
apiVersion: "config.istio.io/v1alpha2"
kind: redisquota
metadata:
  name: handler
  namespace: istio-system
spec:
  redisServerUrl: redis-ratelimit.istio-system:6379
  connectionPoolSize: 10
  quotas:
    - name: requestcount.quota.istio-system
      maxAmount: 500
      validDuration: 1s
      bucketDuration: 500ms
      rateLimitAlgorithm: ROLLING_WINDOW
      overrides:
        - dimensions:
            destination: service-go
          maxAmount: 50
        - dimensions:
            destination: service-node
            source: "10.28.11.20"
          maxAmount: 50
        - dimensions:
            destination: service-node
          maxAmount: 20
        - dimensions:
            destination: service-python
          maxAmount: 2
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
    - handler: handler.redisquota
      instances:
        - requestcount.quota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
    - quotas:
        - charge: 1
          quota: requestcount
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
    - name: request-count
      namespace: istio-system
  services:
    - name: service-go
      namespace: default
    - name: service-node
      namespace: default
    - name: service-python
      namespace: default