kind: PodPreset
apiVersion: settings.k8s.io/v1alpha1
metadata:
  name: myweb-volume-setting
spec:
  selector:
    matchLabels:
      app: myweb
  volumeMounts:
    - mountPath: /html
      name: webpage-volume
  volumes:
    - name: webpage-volume
      emptyDir: {} 