apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: httpbin
spec:
  targets:
  - name: httpbin
  peers:
  - mtls:
      mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: "httpbin.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL