apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: my-nginx
spec:
  peers:
  - mtls: {}
  targets:
  - name: my-nginx
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-nginx
spec:
  host: my-nginx
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL