apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  name: whitelist
spec:
  overrides:
  - "v2"
  entryType: STRINGS
  blacklist: true
---
apiVersion: config.istio.io/v1alpha2
kind: listentry
metadata:
  name: app-version
spec:
  value: source.labels["version"]
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: check-version
spec:
  match: destination.labels["app"] == "service-go"
  actions:
  - handler: whitelist.listchecker
    instances:
    - app-version.listentry