apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: service-js-service-python-viewer
  namespace: default
spec:
  rules:
  - services:
    - "service-js.default.svc.cluster.local"
    - "service-python.default.svc.cluster.local"
    methods: ["GET"]
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-service-js-service-python-viewer
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "service-js-service-python-viewer"
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: service-lua-service-node-viewer
  namespace: default
spec:
  rules:
  - services:
    - "service-lua.default.svc.cluster.local"
    - "service-node.default.svc.cluster.local"
    methods: ["GET"]
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-service-lua-service-node-viewer
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/service-python"
  roleRef:
    kind: ServiceRole
    name: "service-lua-service-node-viewer"
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: service-go-viewer
  namespace: default
spec:
  rules:
  - services: ["service-go.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-service-go-viewer
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/service-node"
  roleRef:
    kind: ServiceRole
    name: "service-go-viewer"