version: '2'
volumes:
  opt-splunk-etc:
  opt-splunk-var:
services:
  splunk:
    image: splunk/splunk
    ports:
      - 8000:8000
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: Admin1234
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    restart: always
  forwarder:
    image: splunk/universalforwarder
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: Admin1234
      SPLUNK_FORWARD_SERVER: splunk:9997
    restart: always
