apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-nginx
spec:
  hosts:
  - "*"
  gateways:
  - https-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - "foo.my-nginx.com"
    route:
    - destination:
        host: my-nginx.foo.svc.cluster.local
        port:
          number: 443
  - match:
    - port: 443
      sniHosts:
      - "bar.my-nginx.com"
    route:
    - destination:
        host: my-nginx.bar.svc.cluster.local
        port:
          number: 443
