apiVersion: v1
kind: Pod
metadata:
  name: dns-test
spec:
  containers:
  - image: radial/busyboxplus:curl
    name: dns-test
    stdin: true
    tty: true
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
