kind: Service
apiVersion: v1
metadata:
  name: servicegraph-test
  namespace: istio-system
  labels:
    app: servicegraph
spec:
  selector:
    app: servicegraph
  type: NodePort
  ports:
    - name: http-servicegraph
      protocol: TCP
      port: 8088
      nodePort: 32145