kind: Service
apiVersion: v1
metadata:
  name: service-redis
  labels:
    app: service-redis
spec:
  selector:
    app: service-redis
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-redis-v1
spec:
  selector:
    matchLabels:
      app: service-redis
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: service-redis
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - name: service-redis
        image: registry.cn-shanghai.aliyuncs.com/istio-lab/service-redis:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi