version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
           - "27018:27017"
    volumes:
        - ./dock/init/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: product