kind: Service
apiVersion: v1
metadata:
  name: service-python
  labels:
    app: service-python
spec:
  selector:
    app: service-python
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-python-v1
spec:
  selector:
    matchLabels:
      app: service-python
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: service-python
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - name: service-python
        image: registry.cn-shanghai.aliyuncs.com/istio-lab/service-python:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-python-v2
spec:
  selector:
    matchLabels:
      app: service-python
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: service-python
        version: v2
    spec:
      restartPolicy: Always
      containers:
      - name: service-python
        image: registry.cn-shanghai.aliyuncs.com/istio-lab/service-python:v2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
