apiVersion: config.istio.io/v1alpha2
kind: logentry
metadata:
  name: newlog
  namespace: istio-system
spec:
  severity: '"info"'
  timestamp: request.time
  variables:
    source: source.labels["app"] | source.workload.name | "unknown"
    user: source.principal | "unknown"
    destination: destination.labels["app"] | destination.service.name | "unknown"
    response_code: response.code | 0
    response_size: response.size | 0
    latency: response.duration | "0ms"
  monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: config.istio.io/v1alpha2
kind: fluentd
metadata:
  name: fluentdhandler
  namespace: istio-system
spec:
  address: "fluentd-es.logging:24224"
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: newlogtofluentd
  namespace: istio-system
spec:
  match: "true"
  actions:
   - handler: fluentdhandler.fluentd
     instances:
     - newlog.logentry