apiVersion: config.istio.io/v1alpha2
kind: metric
metadata:
  name: myrequestcount
  namespace: istio-system
spec:
  value: "1"
  dimensions:
    destination_service: destination.service.name | "unknown"
    destination_namespace: destination.service.namespace | "unknown"
    destination_version: destination.labels["version"] | "unknown"
    response_code: response.code | 200
  monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: config.istio.io/v1alpha2
kind: prometheus
metadata:
  name: myrequestcounthandler
  namespace: istio-system
spec:
  metrics:
  - name: request_count
    instance_name: myrequestcount.metric.istio-system
    kind: COUNTER
    label_names:
    - destination_service
    - destination_namespace
    - destination_version
    - response_code
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: request-count
  namespace: istio-system
spec:
  actions:
  - handler: myrequestcounthandler.prometheus
    instances:
    - myrequestcount.metric