apiVersion: config.istio.io/v1alpha2
kind: metric
metadata:
  name: mytcpsentbytes
  namespace: default
spec:
  value: connection.sent.bytes | 0
  dimensions:
    source_service: source.labels["app"] | source.workload.name | "unknown"
    source_version: source.labels["version"] | "unknown"
    destination_service: destination.service.name | "unknown"
    destination_version: destination.labels["version"] | "unknown"
  monitoredResourceType: '"UNSPECIFIED"'
---
apiVersion: config.istio.io/v1alpha2
kind: metric
metadata:
  name: mytcpreceivedbytes
  namespace: default
spec:
  value: connection.received.bytes | 0
  dimensions:
    source_service: source.labels["app"] | source.workload.name | "unknown"
    source_version: source.labels["version"] | "unknown"
    destination_service: destination.service.name | "unknown"
    destination_version: destination.labels["version"] | "unknown"
  monitoredResourceType: '"UNSPECIFIED"'
---
apiVersion: config.istio.io/v1alpha2
kind: prometheus
metadata:
  name: tcphandler
  namespace: default
spec:
  metrics:
  - name: tcp_sent_bytes
    instance_name: mytcpsentbytes.metric.default
    kind: COUNTER
    label_names:
    - source_service
    - source_version
    - destination_service
    - destination_version
  - name: tcp_received_bytes
    instance_name: mytcpreceivedbytes.metric.default
    kind: COUNTER
    label_names:
    - source_service
    - source_version
    - destination_service
    - destination_version
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: tcp-sent-received-bytes
  namespace: default
spec:
  match: context.protocol == "tcp"
         && destination.service.namespace == "default"
  actions:
  - handler: tcphandler.prometheus
    instances:
    - mytcpreceivedbytes.metric
    - mytcpsentbytes.metric
